name: Upload translations

on:
  push:
    branches: [main]

jobs:
  upload-translations:
    name: Upload translations
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions / checkout
      id-token: write # required for requesting the JWT
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Push translation keys
        run: yarn localazy upload -r ${{ secrets.LOCALAZY_MOBILE_READ_KEY }} -w ${{ secrets.LOCALAZY_MOBILE_WRITE_KEY }}
